spring:
  name: "dv-finance-exchanger"

  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      host: mongodb
      port: 27017
      username: mongodb
      password: mongodb
      database: dv-finance-exchanger

limit:
  trade: 2d